about/urls.py
from django.urls import path
from . import views 

app_name = 'about'

urlpatterns = [
    path('us/', views.about, name='us'),
]

blog/urls.py
from django.urls import path
from . import views 

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='main')
]

contact/urls.py
from django.urls import path
from .views import *

app_name = 'contact'

urlpatterns = [
    # path('me/', ContactView.as_view() , name="me"),
    path('me/', get_in_touch, name="me"),
    
]

game/urls.py
from django.urls import path
from . import views 

app_name = 'game'

urlpatterns = [
    path('', views.list_game, name='liste'),
]

infinity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('game/', include('game.urls')),
    path('contact/', include('contact.urls')),
    path('marketing/', include('marketing.urls')),
    path('tinymce/', include('tinymce.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketing/urls.py
from django.urls import path
from . import views 

app_name = 'marketing'

urlpatterns = [
    path('subscribe/', views.subscription, name='subscribe'),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="fr">
  {% load static %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <title>
      {% block title %} {% endblock title %} Infinity Media
  </title>

  <!-- 
    - favicon
  -->
  <link rel="shortcut icon" href="./favicon.svg" type="image/svg+xml">

  <!-- 
    - custom css link
  -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

  <!-- 
    - google font link
  -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Jost:wght@600;900&family=Poppins:wght@400;500;600;700&display=swap"
    rel="stylesheet">
</head>

<body id="top">

  <!-- 
    - #HEADER
  -->

  <header class="header" data-header>
    <div class="container">

      <div class="overlay" data-overlay></div>
      {% if logo %}
      <a href="/" class="logo">
        <img src="{{ logo.image.url }}" width="68" height="48" alt="{{ logo.text_alternatif|safe|capfirst }}">
      </a>
      {% else %}
      <a href="/" class="logo">
        <img src="{% static 'assets/images/logo.svg' %}" width="68" height="48" alt="Logo">
      </a>
      {% endif %}

      <nav class="navbar" data-navbar>

        <div class="navbar-top">
          <p class="navbar-title">Menu</p>

          <button class="nav-close-btn" aria-label="Close Menu" data-nav-close-btn>
            <ion-icon name="close-circle-outline"></ion-icon>
          </button>
        </div>

        <ul class="navbar-list">

          <li>
            <a href="/" {% if request.path == '/' %}style="color: blue;"{% endif %} class="navbar-link" data-navlink>Accueil</a>
          </li>

          <li>
            <a href="{% url 'game:liste' %}" {% if 'game' in request.path %} style='color:blue;' {% endif %} class="navbar-link" data-navlink>Jeux</a>
          </li>

          <li>
            <a href="{% url 'blog:main' %}" {% if 'blog' in request.path %} style="color:blue;" {% endif %} class="navbar-link" data-navlink>Blog</a>
          </li>

          <li>
            <a href="{% url 'about:us' %}" class="navbar-link" data-navlink>À propos</a>
          </li>
{% comment %} 
          <li>
            <a href="#instruction" class="navbar-link" data-navlink>Instruction</a>
          </li> {% endcomment %}

          <!-- <li>
            <a href="#" class="navbar-link" data-navlink>Contact</a>
          </li> -->

        </ul>

      </nav>

      <button class="menu-open-btn" aria-label="Open Menu" data-nav-open-btn>
        <ion-icon name="menu-outline"></ion-icon>
      </button>

      <a href="{% url 'contact:me' %}" class="btn" aria-labelledby="wallet">
        <ion-icon name="wallet-outline"></ion-icon>

        <span id="wallet">Contactez-nous</span>
      </a>

    </div>
  </header>





  {% block content %}{% endblock content %}






  <footer class="footer">
    <div class="container">

      <div class="footer-top">

        <div class="footer-brand">

          {% if logo %}
          <a href="/" class="logo">
            <img src="{{ logo.image.url }}" width="68" height="48" alt="{{ logo.text_alternatif|safe|capfirst }}">
          </a>
          {% else %}
          <a href="/" class="logo">
            <img src="{% static 'assets/images/logo.svg' %}" width="68" height="48" alt="Logo">
          </a>
          {% endif %}

          {% if media %}
          <p class="footer-text">
            {{ media.intro|safe|capfirst }}
          </p>

          <ul class="social-list">

            <li>
              <a href="{{ media.fb_link }}" target="_blank" class="social-link">
                <ion-icon name="logo-facebook"></ion-icon>
                <ion-icon name="logo-facebook"></ion-icon>
              </a>
            </li>

            <li>
              <a href="{{ media.twitter_link }}" target="_blank" class="social-link">
                <ion-icon name="logo-twitter"></ion-icon>
                <ion-icon name="logo-twitter"></ion-icon>
              </a>
            </li>

            <li>
              <a href="{{ media.instagram_link }}" target="_blank" class="social-link">
                <ion-icon name="logo-instagram"></ion-icon>
                <ion-icon name="logo-instagram"></ion-icon>
              </a>
            </li>

          </ul>
          {% endif %}

        </div>

        <ul class="footer-list">

          <li>
            <p class="footer-list-title">Forum aux questions</p>
          </li>

          <!-- <li>
            <a href="#" class="footer-link">All NFTs</a>
          </li> -->

          <li>
            <a href="#" class="footer-link">FAQ</a>
          </li>

          <li>
            <a href="#" class="footer-link">Créez</a>
          </li>

          <li>
            <a href="#" class="footer-link">Explorez</a>
          </li>

          <li>
            <a href="#" class="footer-link">Confidentialité & Termes</a>
          </li>

        </ul>

        <ul class="footer-list">

          <li>
            <p class="footer-list-title">Liens utiles</p>
          </li>

          <li>
            <a href="/" {% if request.path == '/' %} style='color:blue;' {% endif %} class="footer-link">Accueil</a>
          </li>

          <li>
            <a href="{% url 'game:liste' %}" {% if 'game' in request.path %} style="color:blue;" {% endif %} class="footer-link">Jeux</a>
          </li>

          <li>
            <a href="{% url 'blog:main' %}" {% if 'blog' in request.path %} style="color:blue;" {% endif %} class="footer-link">Blog</a>
          </li>

          <li>
            <a href="#" class="footer-link">Newsletter</a>
          </li>

        </ul>

        <div class="footer-list">

          <p class="footer-list-title">S'inscrire</p>

              <!-- message if email is sent -->
          {% if messages %}
            {% for message in messages %}
              <div class="my-5 alert alert-success">
                <h5 class="m-0">
                    {{ message }}
                </h5>
              </div>
            {% endfor %}
          {% endif %}
          

          <form action="{% url 'marketing:subscribe' %}" class="newsletter-form" method="POST">
              {% csrf_token %}
            <input type="email" name="email" placeholder="Votre adresse email" required class="newsletter-input"> 

            <button type="submit" class="newsletter-btn" aria-label="Submit">
              <ion-icon name="paper-plane-outline"></ion-icon>
            </button>
          </form>

        </div>

      </div>

      <div class="footer-bottom">
        <p class="copyright">
          copyright &copy; {% now "Y" %}
          <!-- &copy; 2022 <a href="#" class="copyright-link">codewithsadee</a>. All Rights Reserved -->
        </p>
      </div>

    </div>
  </footer>




  <!-- 
    - #BACK TO TOP
  -->

  <a href="#top" class="back-to-top" aria-label="Back to Top" data-back-top-btn>
    <ion-icon name="arrow-up-outline"></ion-icon>
  </a>





  <!-- 
    - custom js link
  -->
  <script src="{% static 'assets/js/script.js' %}"></script>

  <!-- 
    - ionicon link
  -->
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>

</html>

<!-- git push https://github.com/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@github.com/keita8/INFINITY.git


git push https://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@github.com/keita8/INFINITY.git
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 -->